version: '3'
services:
  api:
    build: /Backend
    ports:
      - "3000:3000"
    container_name: api
    links:
      - redis
    depends_on:
      - "redis"
    restart: always
  web:
    build: /Frontend/IS
    ports:
      - "80:80"
    container_name: web
    restart: always
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    restart: always
    command: redis-server
  